import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import StoreProvider from "./StoreProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en" data-theme="corporate">
        <body>
          <Navbar />
          <main className="min-h-[100vh] mx-32 my-24">{children}</main>
          <Footer />
        </body>
      </html>
    </StoreProvider>
  );
}
